spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/finans-portal
          jwk-set-uri: http://localhost:8180/realms/finans-portal/protocol/openid-connect/certs